#include: package:pedantic/analysis_options.yaml

# https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml
include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

formatter:
  page_width: 120

# see:
#  https://github.com/dart-lang/linter/tree/master/lib/src/rules
#  https://dart.dev/tools/linter-rules/
linter:
  rules:
    # https://dart.dev/tools/linter-rules/avoid_dynamic_calls
    avoid_dynamic_calls: false

    # https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml
    avoid_equals_and_hash_code_on_mutable_classes: true

    # https://dart.dev/tools/linter-rules/avoid_returning_this
    avoid_returning_this: true

    # https://dart.dev/tools/linter-rules/avoid_final_parameters
    avoid_final_parameters: false

    # https://dart.dev/tools/linter-rules/avoid_slow_async_io
    avoid_slow_async_io: true

    # https://dart.dev/tools/linter-rules/constant_identifier_names
    constant_identifier_names: false

    # https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml
    lines_longer_than_80_chars: false

    # https://dart.dev/tools/linter-rules/literal_only_boolean_expressions
    literal_only_boolean_expressions: true

    # https://dart.dev/tools/linter-rules/omit_local_variable_types
    omit_local_variable_types: true

    # https://dart.dev/tools/linter-rules/prefer_mixin
    prefer_mixin: true

    prefer_single_quotes: true

    # https://dart.dev/tools/linter-rules/require_trailing_commas
    require_trailing_commas: false

    # allow java-style comments
    # https://dart.dev/tools/linter-rules/slash_for_doc_comments
    slash_for_doc_comments: false

    # warn if await is missing on calling async func
    # https://dart.dev/tools/linter-rules/unawaited_futures
    unawaited_futures: true

    # https://dart.dev/tools/linter-rules/unnecessary_brace_in_string_interps
    unnecessary_brace_in_string_interps: false

    # https://dart.dev/tools/linter-rules/unnecessary_lambdas
    unnecessary_lambdas: true

    # https://dart.dev/tools/linter-rules/unnecessary_late
    unnecessary_late: true

    # allow new keyword
    # https://dart.dev/tools/linter-rules/unnecessary_new
    unnecessary_new: false

    # https://github.com/passsy/dart-lint/blob/master/lib/analysis_options.yaml
    use_to_and_as_if_applicable: true
